export { Orb, VoiceOrb } from "./voice-orb";
export { clampVolume, deriveVoiceOrbState, deriveVoiceOrbVolume, normalizeSignal } from "./signals";
export {
  DEFAULT_ORB_LABELS,
  DEFAULT_ORB_MOTION,
  DEFAULT_VOICE_ORB_LABELS,
  DEFAULT_VOICE_ORB_MOTION,
  type OrbAdapter,
  type OrbCloudMode,
  type OrbControlAppearance,
  type OrbControlOptions,
  type OrbControlPosition,
  type OrbHtmlAttributes,
  type OrbLabels,
  type OrbMotion,
  type OrbProps,
  type OrbScale,
  type OrbScaleDefinition,
  type OrbScaleName,
  type OrbScaleOverride,
  type OrbSignal,
  type OrbSignalListener,
  type OrbState,
  type OrbStyle,
  type OrbTheme,
  type OrbToneRamp,
  type OrbTransitions,
  type OrbVisualState,
  type VoiceOrbAdapter,
  type VoiceOrbCloudMode,
  type VoiceOrbControlAppearance,
  type VoiceOrbControlOptions,
  type VoiceOrbControlPosition,
  type VoiceOrbLabels,
  type VoiceOrbMotion,
  type VoiceOrbProps,
  type VoiceOrbScale,
  type VoiceOrbScaleDefinition,
  type VoiceOrbScaleName,
  type VoiceOrbScaleOverride,
  type VoiceOrbSignal,
  type VoiceOrbSignalListener,
  type VoiceOrbState,
  type VoiceOrbStyle,
  type VoiceOrbToneRamp,
  type VoiceOrbTransitions,
  type VoiceOrbVisualState,
} from "./voice-orb.types";
export {
  DEFAULT_ORB_SCALE,
  DEFAULT_VOICE_ORB_SCALE,
  ORB_SCALES,
  VOICE_ORB_SCALES,
  resolveOrbScale,
  resolveVoiceOrbScale,
} from "./voice-orb-scales";
